<template>
    <li class="panel active">
          &nbsp;&nbsp; &nbsp;Please read Anime Sama 's Terms of Service(TOS) carefully before using our app. Anime Sama will do its best to ensure users are updated in regards to any changes. It is your responsibility as a user to periodically review the ToS. Anime Sama may at any point update, change, or modify the ToS and you agree to abide by any changes made. If you do not agree to these terms, then you have no right to access or use the application, services or site content.
          <p>1.General Use of the App</p>
          Anime Sama hereby grants you permission to access and use the App as set forth in these Terms of Service, provided that:<br>
          A. You agree not to distribute in any medium any part of the APP, including but not limited to User Content (defined below), without Anime Sama's prior written authorization.<br>
          B. You agree not to alter or modify any part of the App.<br>
          C. You agree not to access User Content (defined below) or Anime Sama Content through any technology or means other than the App itself.<br>
          D. You agree not to use the App for any commercial use, without the prior written authorization of Anime Sama. Prohibited commercial uses include any of the following actions taken without Anime Sama's express approval:  <br>
          <ul>
            <li>sale of access to the App or its related services on another website/App;Due to the same interests, we become friends and can chat whenever and wherever possible.</li>
            <li>use of the App or its related services for the primary purpose of gaining advertising or subscription revenue;</li>
            <li>the sale of advertising, on the Anime Sama App or any third-party website/App, targeted to the content of specific User Content or Anime Sama content;</li>
            <li>and any use of the App or its related services that Anime Sama finds, in its sole discretion, to use Anime Sama's resources or User Content with the effect of competing with or displacing the market for Anime Sama , Anime Sama content, or its User Content.</li>
          </ul>
          E. You agree not to use or launch any automated system, including without limitation, "robots," "spiders," or "offline readers," that accesses the App in a manner that sends more request messages to the Anime Sama servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding, Anime Sama grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. Anime Sama reserves the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the App, nor to use the communication systems provided by the App (e.g.comments, email, messages, notes) for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the App with respect to their User Content.  <br>
          F. In your use of the App, you will otherwise comply with the terms and conditions of these Terms of Service and all applicable local, national, and international laws and regulations.   <br>
          G. Anime Sama reserves the right to discontinue any aspect of the Anime Sama App at any time.
          <p>2. Account Registration</p>
          As a condition to using certain of the Service, you may be required to create an account. Where you are required to register:<br>
          A. You must provide us with accurate, complete and current registration information;<br>
          B. You are responsible for maintaining the confidentiality of your Account password and for the security of your Account, and you will notify Anime Sama immediately of any actual or suspected loss, theft, or unauthorized use of your Account or Account password;<br>
          C. You authorize us to assume that any person using Anime Sama Services with your user name and/or password is either you or is authorized to act for you;<br>
          D. You cannot do to impersonate any person or entity, including, but not limited to, or falsely state or otherwise misrepresent your affiliation with a person or entity (fiction marked as such, including real-person fiction in first-person format, is not subject to this policy);<br>
          E. You may cancel your registration at any time by notifying us; and we reserve the right to discontinue or cancel your registration in our sole and absolute discretion without notice to you if you do not use ToS for an extended period of time, if you breach any of these terms and conditions or any applicable law, if we conclude that your conduct impacts on name or reputation or violates our rights or those of another party, or as we otherwise think fit.<br>
          F. If you chose to cancel your account or if your account is otherwise terminated by us, all of your user content may remain on the Anime Sama Services even after your account has been canceled.
          <p>3. Disclaimer about Location Data</p>
          3.1 Anime Sama Services are intended only as personal, location-based sevices for in dividual use and should not be used or relied on as an emergency locator system, used while driving or operating vehicles, or used in connection with any hazardous environments requiring fail-safe performance, or any other application in which the failure or inaccuracy of that application or the Anime Sama Services could lead dirctly to death, personal injury, or severe physical or property damage.<br>
          3.2 Anime Sama is not suited or intended for family finding purposes, fleet tracking, or any other type of business or enterprise use- other product exist today that may be used specifically for these purposes.<br>
          <p>4. Use of Content on the App</p>
          The following restrictions and conditions apply specifically to your use of content on the Anime Sama App.<br>
          4.1 The content on the Anime Sama App, except all User Content (as defined below), including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like ("Content") and the trademarks, service marks and logos contained therein ("Marks"), are owned by or licensed to Anime Sama, subject to copyright and other intellectual property rights under the law. Content on the APP is provided to you AS IS for your information and personal use only and may not be downloaded, copied, modified, produced, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, translated, published, performed or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Anime Sama reserves all rights not expressly granted in and to the APP and the Content.<br>
          4.2 You may access User Content solely:<br>
          A. for your information and personal use;<br>
          B. as intended through the normal functionality of the Anime Sama Service;<br>
          4.3 You may access Anime Sama Content, User Content and other content only as permitted under this Agreement. Anime Sama reserves all rights not expressly granted in and to the Anime Sama Content and the Anime Sama Service.<br>
          4.4 You agree to not engage in the use, copying, or distribution of any of the Content other than expressly permitted herein, including any use, copying, or distribution of User Content of third parties obtained through the APP for any commercial purposes.<br>
          4.5 You agree not to circumvent, disable or otherwise interfere with security-related features of the Anime Sama APP or features that prevent or restrict use or copying of any Content or enforce limitations on use of the Anime Sama APP or the Content therein.<br>
          4.6 You understand that when using the Anime Sama APP, you will be exposed to User Submissions from a variety of sources, and that Anime Sama APP is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Content. You further understand and acknowledge that you may be exposed to User Content that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Anime Sama with respect thereto, and agree to indemnify and hold Anime Sama, its Owners/Operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the site.
          <p>5. User Content</p>
          5.1 As an Anime Sama account holder you may submit textual, audio, visual, or audiovisual content including but not limited to stories, poetry, polls, profile images, posts' comments or instant messages. User submitted content are collectively referred to as "User Content." You understand that whether or not such User SContent are published, Anime Sama does not guarantee any confidentiality with respect to any User Content.<br>
          5.2 You shall be solely responsible for your own User Content and the consequences of posting or publishing them. In connection with User Content, you affirm, represent, and/or warrant that: you own or have the necessary licenses, rights, consents, and permissions to use and authorize Anime Sama to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content and have all necessary consents to collect, use and disclose any personally identifiable information contained or displayed in any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the App and these Terms of Service.<br>
          5.3 For clarity, you retain all of your ownership rights in your User Content. However, by submitting User Content to Anime Sama, you hereby grant Anime Sama a worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, distribute, display, and perform the User Content in connection with the Anime Sama App. You also hereby waive any moral rights you may have in your User Content and grant each user of the Anime Sama APP a non-exclusive license to access your User Content through the App. You understand and agree, however, that Anime Sama may retain, but not display, distribute, or perform, server copies of User Content that have been removed or deleted.<br>
          5.4 In connection with User Content, you further agree that you will not submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner and the necessary consents from any individuals whose personally identifiable information is contained in such material to post the material and to grant Anime Sama all of the license rights granted herein.<br>
          5.5 You further agree that you will not, in connection with User Content, submit material that is contrary to applicable local, national, and international laws and regulations.<br>
          5.6 Anime Sama does not endorse any User Content or any opinion, recommendation, or advice expressed therein, and Anime Sama expressly disclaims any and all liability in connection with User Content. Anime Sama does not permit copyright infringing activities and infringement of intellectual property rights on its App, and Anime Sama will remove all Content and User Content if properly notified that such Content or User Content infringes on another's intellectual property rights or contravenes any applicable privacy legislation. Anime Sama reserves the right to remove Content and User Content without prior notice.<br>
          <p>6. Copyright Policy</p>
          As part of Anime Sama's copyright policy, Anime Sama may terminate user access to the App if a user has been determined to be an infringer. To file a copyright infringement notification with us, you will need to send a communication to us with all of the following information in it, using this format:<br>
          A. Include a statement telling us that you have found a content on Anime Sama which you believe infringes your copyright (for example, "I hereby confirm that I believe the story identified below infringes my copyright").<br>
          Tell us which country your copyright applies to.<br>
          B. Tell us the details of (e.g. title, user ID, dates, etc.) the content concerned.<br>
          C. Explain to us in what way that content infringes your copyright (e.g. the text is copied, the entire story is a copy of an original work made by you, etc.)<br>
          D. Identify the type (e.g. a book, a short story, a poem, etc.). and details of (e.g. title, publisher, dates, etc.) the copyright work which you own the rights in, and which you believe has been infringed. If this information is available on the internet, it is helpful to send us a link.<br>
          E. Let us have contact information so that we can get in touch with you (email address is preferred).<br>
          F. Let us have the contact information which we can pass on to the submitter of the content concerned, so that they can get in touch with you to resolve your complaint directly (email address is preferred).<br>
          G. Include the following statement: "I have a good faith belief that use of the copyrighted work described above is not authorized by the copyright owner (or by a third party who is legally entitled to do so on behalf of the copyright owner) and is not otherwise permitted by law."<br>
          H. I swear that the information contained in this notification is accurate and that I am the copyright owner or have an exclusive right in law to bring infringement proceedings with respect to its use.<br>
          I. Sign the notice. If you are providing notice by e-mail, a scanned physical signature or a valid electronic signature will be accepted.<br>
          J. Send the notice, in English, to the following address: <br>
          Attn: FanFiction.Net Copyright Infringement Notification <br>
          Email: AnimeSamaFans@gmail.com <br> 
          Please also note that the information provided in this legal notice may be forwarded to the person who provided the allegedly infringing content.<br>
          Make sure you know whether the content that you have seen on Anime Sama infringes your copyright. Be aware that there may be adverse legal consequences in your country if you make a false or bad faith allegation of copyright infringement by using this process.<br>
          <p>7. Warranty Disclaimer</p>
          7.1 The Anime Sama service is provided "as is" without any representations or warranties, express or implied. Anime Sama excluedes all representations and warranties to the full extent permissible under applicable law.<br>
          7.2 Anime Sama makes no representations or warranties in relation to the Anime Sama Services or the content, information and materials on the Anime Sama platform.<br>
          7.3 Anime Sama does not warrant the Anime Sama plattform will be constantly available or available at all.<br>
          7.4 Anime Sama does not warrant that the content on the Anime Sama platform is complete, true, accurate, non-misleading, non-infringing, leagal or decent.<br>
          7.5 You use the Anime Sama platform at your risk. You must evaluate and bear all risks assocaited with the use of any material or content, including reliance on the accuracy, completeness or usefulness of any material or content.<br>
          7.6 Anime Sama does not guarantee that your requirements will be met or that any content will be uninterrupted, error free or that the Anime Sama platform or the server that operates the Anime Sama platform is free of viruses or other harmful components.<br>
          7.7 Anime Sama assumes no liability or reponsibility for any:<br>
          7.7.1 Errors, mistakes, or inaccuracies of content,<br>
          7.7.2 Personal injury or property damage, of any nature whatsoever, resulting from your access to and use of the Anime Sama platform,<br>
          7.7.3 Any unauthorized access to or use of Anime Sama servers and/or any and all personal information and/or financial information stored therein,<br>
          7.7.4 Any interruption or cessation of transmission to or from the Anime Sama platform.<br>
          7.8 Anime Sama does not warrent, endorse, guarantee, or assume responsibility for any product or service advertised or offered through the Anime Sama plafrom and Anime Sama will not be a party or in an way be responsible for monitoring any transaction between you and third-party providers of prodcuts or services.<br>
          8. Third-Party Sites, Products and Services; Links<br>
          8.1 The Anime Sama Services may include links to other web sites or services solely as a convenience to Users. Anime Sama does not endorse any such linked sites or the information, material, products or services contained on other linked sites or accessible through other linked sites.<br>
          8.2 Furthermore, Anime Sama makes no express or implied warranties with regard to the information, material, products or services that are contained on or accessible through linked sites.<br>
          8.3 Access and use of linked sites, including information, material, products and services on linked sites or available through linked sites is solely at your own risk.<br>
          8.4 Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Anime Sama Services are solely between you and such advertiser.<br>
          8.5 You agree that Anime Sama shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such delings or as the result of the presence of such advertisers on the Anime Sama Services.<br>
          8.6 Parties other than Anime Sama may provide services or sell products via the Anime Sama Services. We are not respoinsible for examing or evaluating, and we do not warrant the offerings of, any of these businesses or the content of their product and service offering. Anime Sama does not assume any responsibility or liability for the actions, product, and content of all these and any other third parties. You should carefully review their privacy statements and other terms and conditions of use.<br>
          <p>9.General Provisions</p>
          Matters not specifically addressed in this agreement will be governed by the general Terms of Service.<br>
        </li>
</template>

